#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done


if [ ! -f /tmp/state/10-nginx ]; then

  ### Make sure that DB is accessible
  while true; do
    mysqlcmd='mysql -u'$DB_USER' -h'$DB_HOST' -p'$DB_PASS 
    out="`$mysqlcmd -e "SELECT COUNT(*) FROM information_schema.FILES;" 2>&1`"
    echo "$out" | grep -E "COUNT|Enter" 2>&1 > /dev/null
    if [ $? -eq 0 ]; then
      echo "[osticket] Server is up !"
      break
    fi
    echo "[osticket] Server "$DB_HOST" is not available. Retying in 2 seconds"
    sleep 2
  done

  ### Adjust Runtime Variables
  sed -i -e "s/<CRON_PERIOD>/$CRON_PERIOD/g" /assets/cron/crontab.txt

  ### Check to see if this is a new install, if yes copy information from assets create directories...
  if [ ! -f /www/osticket/upload/index.php ] ; then
     echo "** [osticket] ** New OSTicket Installation Detected......"
     cp -R /assets/osticket /www/
     chown -R nginx:www-data /www/osticket/upload/
     chmod -R a+rX /www/osticket/upload/ /www/osticket/scripts/
     chmod -R u+rw /www/osticket/upload/ /www/osticket/scripts/
     chown -R root:root /www/osticket/upload/setup_hidden
     chmod 700 /www/osticket/upload/setup_hidden
  fi

  # Automate installation
  php /assets/install.php

  ## Check Memcache Settings
  if [ ${MEMCACHE_HOST:+1} ]
  then
      echo "** [osticket] Setting Memcache.."
      sed -i -e "s/# define('SESSION_BACKEND', 'memcache');/define('SESSION_BACKEND', 'memcache');/g" /www/osticket/upload/include/ost-config.php
      sed -i -e "s/# define('MEMCACHE_SERVERS', 'server1:11211,server2:11211');/define('MEMCACHE_SERVERS', '$MEMCACHE_HOST:11211');/g" /www/osticket/upload/include/ost-config.php
  fi
  ## Proxy Fix
  if [ ${VIRTUAL_HOST:+1} ]
  then
      echo "** [osticket] Configuring Reverse Proxy settings.."
      sed -i -e "s/define('TRUSTED_PROXIES', '');/define('TRUSTED_PROXIES', '*');/g" /www/osticket/upload/include/ost-config.php
  fi

  echo '** [osticket] Applying configuration file security..'
  chmod 644 /www/osticket/upload/include/ost-config.php

  if [ ${ADMIN_PASS:+1} ]
  	then
  	echo 'Setting Administrative User Password'
      mysqlcmd='mysql -u'$DB_USER' -h'$DB_HOST' -p'$DB_PASS 
      $mysqlcmd -e "use "$DB_NAME"; UPDATE "$DB_PREFIX"staff SET passwd = MD5( '"$ADMIN_PASS"' ) WHERE username = '"$ADMIN_USER"';"
  fi

  ### Force Reset Permissions for Security
  chown -R nginx:www-data /www/osticket
  chown -R nginx:www-data /www/osticket/upload/ 
  chmod -R a+rX /www/osticket/upload/ /www/osticket/scripts/
  chmod -R u+rw /www/osticket/upload/ /www/osticket/scripts/
  chown -R root:root /www/osticket/upload/setup_hidden 
  chmod 700 /www/osticket/upload/setup_hidden

  ## Start nginx
  mkdir -p /tmp/state
  echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo '** [osticket] Starting Nginx'
exec nginx